services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leworldcup
    ports:
      - "5432:5432"
    volumes:
      - leworldcup_db:/var/lib/postgresql/data

volumes:
  leworldcup_db:
